### PR TITLE
Dr thom

### PR DESCRIPTION
**Pull request by Dr-Thom**

### CODE REVIEW

**Comment by gervanpn** [comment]
Thom - You have this going to master - Closing it

**Comment by Dr-Thom** [comment]
right. it wasn't a new pull request. i started a DRAFT only to see if i
could fix the sign up issue. had no luck so i abandoned it.

**Comment by gervanpn** [comment]
i closed it because it was to master and there were so many files that it would have changed even if it was to develop.

Gervan Nantel
gervann@yahoo.ca

**Comment by Dr-Thom** [comment]
good

**Pull request closed without merging**
